GET http://localhost:1234/

### Para obtener las peliculas
GET http://localhost:1234/movies

### Para obtener una pelicula en especifico
GET http://localhost:1234/movies/df747343-b41d-11ee-a3f6-d03957c27b84

### Para obtener peliculas basadas en un genero
GET http://localhost:1234/movies?genre=biography

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "Gordo estupido",
  "year": 2000,
  "director": "jaja ekis de jaja",
  "duration": 140,
  "poster": "https://www.informador.mx/export/sites/elinformador/img/2023/04/04/fs3w6biayaa0teb.jpg_1064668086.jpg",
  "genre": ["Action", "Fantasy"],
  "rate": 1
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/6bf75840-b8c2-11ee-ba00-bceca00df178
Content-Type: application/json

{
  "year": 2010,
  "title": "Gordo fuertemenete estupido y enfermo",
  "rate": 2.0,
  "duration": 10,
  "director": "Tu madre la peppa pig"
}

### Borrar una pelicula
DELETE http://localhost:1234/movies/75da7ea6-b73b-11ee-85d6-d03957c27b84
