###Recuperar info del pokemon "Ditto"
GET http://localhost:1234/pokemon/ditto

###Ir a la pagina About
GET http://localhost:1234/about


###Para crear un pokemon
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": ["transform"]
}